{{- if .Values.healthlog.enabled }}
{{- $src_topic := .Values.kafka.srcTopic }}
{{- $sink_topic := .Values.healthlog.sinkTopic }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kse.fullname" . }}-healthlog
  labels:
    {{- include "kse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.healthlog.replicas }}
  selector:
    matchLabels:
      {{- include "kse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.healthlog.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kse.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-kafka
        image: bitnami/kafka:latest
        imagePullPolicy: IfNotPresent
        command: 
        - bash 
        - -c 
        - |
          # wait for kafka broker and source topic to be ready
          sleep 10
          while true; do
            EXISTING_TOPICS=$(kafka-topics.sh --bootstrap-server {{ .Release.Name }}-kafka-headless:9092 --list 2> /dev/null)
            if [ $? -ne 0 ]; then
              echo "Kafka broker not ready. retrying..."
              sleep 5
            # check source topic exists
            elif echo $EXISTING_TOPICS | grep -w "{{ $src_topic }}" > /dev/null; then
              echo "Source topic '{{ $src_topic }}' exists."
              break
            else
              echo "Source topic '{{ $src_topic }}' does not exist. waiting..."
              sleep 5
            fi
          done

          # Create sink topic if not exists
          while true; do
            EXISTING_TOPICS=$(kafka-topics.sh --bootstrap-server {{ .Release.Name }}-kafka-headless:9092 --list 2> /dev/null)
            # check if sink topic already exists
            if echo $EXISTING_TOPICS | grep -w "{{ $sink_topic }}" > /dev/null; then
              echo "Sink topic A '{{ $sink_topic }}' already exists."
              break
            else
              echo "Sink topic A '{{ $sink_topic }}' does not exist. creating..."
              kafka-topics.sh --bootstrap-server {{ .Release.Name }}-kafka-headless:9092 --create --topic {{ $sink_topic }} 2> /dev/null
              if [ $? -eq 0 ]; then
                echo "Sink topic A '{{ $sink_topic }}' creation successful."
                break
              else
                echo "Sink topic A creation failed, retrying..."
                sleep 5             
              fi            
            fi
          done
      containers:
        - name: {{ .Chart.Name }}-healthlog
          image: '{{ include "kse.image" .Values.healthlog.image }}'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: KAFKA_BROKER
            value: {{ .Release.Name }}-kafka-headless:9092
          - name: KAFKA_SOURCE_TOPIC
            value: {{ .Values.kafka.srcTopic }}
          - name: KAFKA_SINK_TOPIC
            value: {{ .Values.healthlog.sinkTopic }}
          resources:
            {{- toYaml .Values.healthlog.resources | nindent 12 }}
      {{- with .Values.healthlog.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.healthlog.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.healthlog.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}