apiVersion: skaffold/v4beta3 
kind: Config 

build: 
  artifacts:
  - image: kse-producer
    context: producer
  - image: kse-filterkey
    context: filterkey

deploy:
  # Kafka 브로커 안정화될 때가지 몇 번의 에러가 발생하기에 실패를 허용하고, 데드라인까지 기다림
  tolerateFailuresUntilDeadline: true 
  helm:
    releases:
    - name: kse
      chartPath: helm
      skipBuildDependencies: true
      setValueTemplates:
        producer.image.registry: '{{ .IMAGE_DOMAIN_kse_producer }}'
        producer.image.repository: '{{ .IMAGE_REPO_NO_DOMAIN_kse_producer }}'
        producer.image.tag: '{{ .IMAGE_TAG_kse_producer }}'
        filterkey.image.registry: '{{ .IMAGE_DOMAIN_kse_filterkey }}'
        filterkey.image.repository: '{{ .IMAGE_REPO_NO_DOMAIN_kse_filterkey }}'
        filterkey.image.tag: '{{ .IMAGE_TAG_kse_filterkey }}'

profiles:
- name: filterkey 
  patches: 
  - op: add 
    path: /deploy/helm/releases/0/valuesFiles 
    value: 
    - configs/filterkey.yaml

  