apiVersion: v2
name: kse
description: Kafka Streams 예제를 위한 차트

type: application

version: 0.0.2

appVersion: "0.0.2"

dependencies:
  - name: kafka
    version: 23.0.1
    repository: https://charts.bitnami.com/bitnami