# 카프카 설정
kafka: 
  # 토픽 기본 파티션 수
  numPartitions: 2
  srcTopic: default-src
  srcTopic2: ""

# 로그 생성기 설정
producer:
  enabled: true
  image:
    registry: ""
    repository: "library/kse-producer"
    tag: 0.0.5
  # 로그 생성 타입
  type: default

# filterkey 예제 
filterkey:
  enabled: false
  # 파드 수
  replicas: 2
  image:
    registry: ""
    repository: "library/kse-filterkey"
    tag: 0.0.5
  sinkTopic: filterkey-sink

# hashsplit 예제 
hashsplit:
  enabled: false
  # 파드 수
  replicas: 1
  image:
    registry: ""
    repository: "library/kse-hashsplit"
    tag: 0.0.5
  sinkTopic: hashsplit-sink
  sinkTopic2: hashsplit-sink2

# multistr 예제 
multistr:
  enabled: false 
  # 파드 수
  replicas: 1
  image:
    registry: ""
    repository: "library/kse-multistr"
    tag: 0.0.5
  sinkTopic: multistr-sink
  sinkTopic2: multistr-sink2

# healthlog 예제 
healthlog:
  enabled: false 
  # 파드 수
  replicas: 1
  image:
    registry: ""
    repository: "library/kse-healthlog"
    tag: 0.0.5
  sinkTopic: healthlog-sink
  sinkTopic2: healthlog-sink2
